### ISSUE TITLE
Cambiar para que parse devuelva un array y toJsSourceCode reciba ese array

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/js-from-html#2]
parse en vez de devolver un objeto devuelve un array de objetos. Así se puede contemplar el siguiente input:

``` html
<p>uno</p>
<p>dos</p>
```

que devolverá: `[html.p("uno"), html.p("dos")]`

toJsSourceCode recibirá un array y devolverá una concatenación de sources separados por coma. O sea un txt multilinea que contiene:

``` txt
html.p("uno"), 
html.p("dos"),
```

**Comment by diegoefe** [comment]
Ya está
