### ISSUE TITLE
El texto multilínea hay que ponerlo en múltiples strings

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/js-from-html#6]
Por ejemplo:

``` html
<pre>linea 1
linea 2
linea 3
</pre>
```

Debe quedar como

``` js
html.pre(
    "linea 1\n"+
    "linea 2\n"+
    "linea 3\n"
),
```

Lo mismo si hay mix de contenido:

``` html
<p>
Uno <b>bold</b> y
luego otro</p>
```

queda

``` js
html.p(
    "\n"+
    "Uno ",
    html.b("bold"),
    " y\n"+
    " luego otro",
), 
```

**Comment by diegoefe** [comment]
No falta un "\n" debajo de https://github.com/codenautas/js-from-html/blob/master/test/fixtures/pseudo-pp.js#L15?
Donde dice:

``` javascript
html.pre(
        "\n"+
        "Array.prototype.forEach.call(document.body.childNodes, function(node){\n"+
        "    console.log(JSON.stringify(node.textContent));\n"+
        "});\n"
    ),
```

No debería decir?

``` javascript
html.pre(
        "\n"+
        "Array.prototype.forEach.call(document.body.childNodes, function(node){\n"+
        "    console.log(JSON.stringify(node.textContent));\n"+
        "});\n"+
        "\n"
    ),
```

**Comment by emilioplatzer** [comment]
Puede ser. Hay que mirar cómo queda el textContent metiendo el html de la
entrada

**Comment by diegoefe** [comment]
No te entiendo

**Comment by emilioplatzer** [comment]
Opino que conviene hacer lo que haga el navegador. Pruebo con Chrome y utilizo el inspector y la consola obteniendo:

![inspect1](https://cloud.githubusercontent.com/assets/5725064/14649173/3e18a3ae-063c-11e6-9009-fa34a193827c.PNG)

cuando miro veo que el último "\n" no está, veo uno solo.

![inspect2](https://cloud.githubusercontent.com/assets/5725064/14649194/56f492e8-063c-11e6-8bc9-d7c24f071a95.PNG)
